FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY worker.py worker.py
CMD ["python", "worker.py"]